### ISSUE TITLE
In sede di cambio residenza, non riesco a validare la Email.

### ISSUE THREAD

**Issue by Nibbio1684** [italia/anpr#3513]
Salve
ho una dichiarazione di residenza in sospeso, che non mi fa inviare perché è necessario specificare e validare un indirizzo Email. Fornisco l'indirizzo Email nella sezione Profilo utente, ricevo l'Email per validare l'indirizzo ma il link mi rimanda ad una pagina blu vuota. Quindi niente conferma dell'Email, e di conseguenza la dichiarazione di cambio residenza resta sospesa. Grazie in anticipo per l'aiuto

**Comment by Saipira1986** [comment]
Salve, riscontro lo stesso problema. Grazie

**Comment by giampa** [comment]
Stesso problema, in console seguente errore:

Refused to execute script from 'https://sc.anpr.interno.it/serviziCittadino/dist/js/verificaemail.bundle.d90e7b115fbbc18b6a75.min.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

Navigando la risorsa direttamente, altri errori dello stesso genere.

**Comment by apaolacci** [comment]
Salve,
grazie delle segnalazione. Adesso dovrebbe funzionare.

Dovreste riprovare ad effettuare un nuovo aggiornamento email e validare l'indirizzo, nel caso riscontrate ancora l'errore e la pagina blu segnalatecelo prontamente.

Grazie,
Assistenza ANPR

**Comment by Nibbio1684** [comment]
Salve,
sono riuscito a validare l'Email correttamente. Grazie per il supporto e la tempestività.
Buona giornata

**Comment by Saipira1986** [comment]
Risolto, grazie

**Comment by giampa** [comment]
Risolto anche io, grazie.
