### ISSUE TITLE
ANPR ferma

### ISSUE THREAD

**Issue by Maga63** [italia/anpr#3955]
Buongiorno, si segnala impossibilità a raggiungere ANPR sia tramite i servizi che trami Web App e anche il rilascio CIE è bloccato.

Comune di Milano

**Comment by siscomanpr** [comment]
Anche i nostri clienti ci stanno segnalando errori di anpr "Malformed content (from server) "

**Comment by dierossi** [comment]
Anche il Comune di Parma è fermo sia con le CIE che con qualsiasi comunicazione con ANPR

**Comment by agnese2023** [comment]
Ho da pochissimo chiamato il numero verde ANPR : l'operatore cadeva dalle nuvole ma dopo poco ha segnalato che altri comuni stavano comunicando il disservizio.

**Comment by agnese2023** [comment]
Comune di Novellara: ho chiamato ora il numero verde ANPR - stavano incominciando a segnalare i disservizi anche su ANPR oltre che su CIE.

**Comment by AntoKay** [comment]
Scisciano (NA) ferma.

Il gestionale va a rilento, il portale CIE segnala ANPR non disponibile.

**Comment by mttfranci** [comment]
@Maga63 @siscomanpr  @agnese2023  @AntoKay @dierossi @iessicatoro  potete verificare se ora riuscite a lavorare correttamente? Grazie in anticipo

**Comment by agnese2023** [comment]
A Novellara il servizio ora funziona... anche se con rallentamenti significativi! 
Grazie! 
Cordialmente, 

Agnese Piacentini 
URP - Comune di Novellara 
TEL. 0522 655417 


Da: "Matteo" ***@***.***> 
A: "italia/anpr" ***@***.***> 
Cc: "Agnese Piacentini" ***@***.***>, "Mention" ***@***.***> 
Inviato: Venerdì, 16 giugno 2023 11:17:10 
Oggetto: Re: [italia/anpr] ANPR ferma (Issue #3955) 





[ https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2FMaga63&e=a39aa7eb&h=13c80c57&f=y&p=n | @Maga63 ] [ https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fsiscomanpr&e=a39aa7eb&h=3c1f4da1&f=y&p=n | @siscomanpr ] [ https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fagnese2023&e=a39aa7eb&h=fa01c11b&f=y&p=n | @agnese2023 ] [ https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2FAntoKay&e=a39aa7eb&h=b5b5a314&f=y&p=n | @AntoKay ] [ https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fdierossi&e=a39aa7eb&h=f54bf101&f=y&p=n | @dierossi ] [ https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fiessicatoro&e=a39aa7eb&h=723cc8fe&f=y&p=n | @iessicatoro ] potete verificare se ora riuscite a lavorare correttamente? Grazie in anticipo 

— 
Reply to this email directly, [ https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fitalia%2Fanpr%2Fissues%2F3955%23issuecomment-1594379582&e=a39aa7eb&h=52301fd7&f=y&p=n | view it on GitHub ] , or [ https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FBATVBRYSZ2RXMYH7AVXB7PLXLQQBNANCNFSM6AAAAAAZI35TDQ&e=a39aa7eb&h=d1621a19&f=y&p=n | unsubscribe ] . 
You are receiving this because you were mentioned. Message ID: <italia/anpr/issues/3955/1594379582 @ github . com> 

-- 
Questo messaggio e' stato analizzato ed e' risultato non infetto. 
This message was scanned and is believed to be clean.

**Comment by AntoKay** [comment]
> @Maga63 @siscomanpr @agnese2023 @AntoKay @dierossi @iessicatoro potete verificare se ora riuscite a lavorare correttamente? Grazie in anticipo

back on track, grazie per l'assistenza.

buon lavoro a tutti i colleghi ;)

**Comment by dierossi** [comment]
> @Maga63 @siscomanpr @agnese2023 @AntoKay @dierossi @iessicatoro potete verificare se ora riuscite a lavorare correttamente? Grazie in anticipo

Anche a Parma i servizi sono ripartiti.....

Saluti

Diego
